# Generated by Django 5.2.7 on 2025-10-18 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('dateCommande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='utilisateur.client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
    ]
