# Generated by Django 5.2.7 on 2025-10-14 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('nomProduit', models.CharField(max_length=255)),
                ('descriptionProduit', models.TextField(blank=True)),
                ('prixUnitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('datePublication', models.DateTimeField(auto_now_add=True)),
                ('id_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='category.category')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='utilisateur.vendeur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
    ]
