# Generated by Django 5.2.7 on 2025-11-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_alter_produit_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
