# Generated by Django 5.2.7 on 2025-10-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_user', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('client', 'Client'), ('vendeur', 'Vendeur'), ('admin', 'Administrateur')], max_length=20)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateur.utilisateur')),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='utilisateur.utilisateur')),
                ('entreprise', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
