# Generated by Django 5.2.7 on 2025-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('nomCategory', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
