# Generated by Django 5.2.7 on 2025-10-18 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id_payement', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('montant', models.FloatField()),
                ('typePayement', models.CharField(max_length=30)),
                ('datePayement', models.DateTimeField(auto_now_add=True)),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payement', to='commande.commande')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payement', to='utilisateur.client')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
