# Generated by Django 5.2.7 on 2025-10-22 15:26

import api.payement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='id_payement',
            field=models.CharField(default=api.payement.models.generate_payement_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payement',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payement', to=settings.AUTH_USER_MODEL),
        ),
    ]
