# Generated by Django 5.2.7 on 2025-10-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0001_initial'),
        ('produit', '0002_alter_produit_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id_ligne', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('quantiteCommande', models.FloatField()),
                ('sousTotal', models.FloatField()),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligneCommandes', to='commande.commande')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligneCommandes', to='produit.produit')),
            ],
            options={
                'verbose_name': 'LigneCommande',
                'verbose_name_plural': 'LigneCommandes',
            },
        ),
    ]
