# Generated by Django 5.2.7 on 2025-11-06 12:14

import api.notifvendeur.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0003_produit_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifVendeur',
            fields=[
                ('id_notif', models.CharField(default=api.notifvendeur.models.generate_id_notif, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('validation', 'Validation'), ('refus', 'Refus')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produit.produit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifvendeurs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
