# Generated by Django 5.2.7 on 2025-10-19 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0002_alter_produit_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id_prom', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('prixAvant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prixApres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='produit.produit')),
            ],
        ),
    ]
